# Generated by Django 3.1.5 on 2022-04-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Bookname', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Noofbooks', models.IntegerField(max_length=10)),
            ],
        ),
    ]
