# Generated by Django 3.1.5 on 2022-04-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSAdmin', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Noofbooks',
            field=models.IntegerField(),
        ),
    ]
